DROP TABLE IF EXISTS admin_reports CASCADE;
DROP TABLE IF EXISTS reports CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS carts CASCADE;
DROP TABLE IF EXISTS price_entries CASCADE;
DROP TABLE IF EXISTS receipts CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS admins CASCADE;
DROP TABLE IF EXISTS store_owners CASCADE;
DROP TABLE IF EXISTS stores CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;

\i '../schema/schema.sql'
\i 'everything.sql'
