/**
 *
 *  AdminReports.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "AdminReports.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::main;

const std::string AdminReports::Cols::_admin_account_id = "\"admin_account_id\"";
const std::string AdminReports::Cols::_report_id = "\"report_id\"";
const std::vector<std::string> AdminReports::primaryKeyName = {"admin_account_id","report_id"};
const bool AdminReports::hasPrimaryKey = true;
const std::string AdminReports::tableName = "\"admin_reports\"";

const std::vector<typename AdminReports::MetaData> AdminReports::metaData_={
{"admin_account_id","int32_t","integer",4,0,1,1},
{"report_id","int32_t","integer",4,0,1,1}
};
const std::string &AdminReports::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
AdminReports::AdminReports(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["admin_account_id"].isNull())
        {
            adminAccountId_=std::make_shared<int32_t>(r["admin_account_id"].as<int32_t>());
        }
        if(!r["report_id"].isNull())
        {
            reportId_=std::make_shared<int32_t>(r["report_id"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            adminAccountId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            reportId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

AdminReports::AdminReports(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            adminAccountId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            reportId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

AdminReports::AdminReports(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("admin_account_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["admin_account_id"].isNull())
        {
            adminAccountId_=std::make_shared<int32_t>((int32_t)pJson["admin_account_id"].asInt64());
        }
    }
    if(pJson.isMember("report_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["report_id"].isNull())
        {
            reportId_=std::make_shared<int32_t>((int32_t)pJson["report_id"].asInt64());
        }
    }
}

void AdminReports::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            adminAccountId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            reportId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

void AdminReports::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("admin_account_id"))
    {
        if(!pJson["admin_account_id"].isNull())
        {
            adminAccountId_=std::make_shared<int32_t>((int32_t)pJson["admin_account_id"].asInt64());
        }
    }
    if(pJson.isMember("report_id"))
    {
        if(!pJson["report_id"].isNull())
        {
            reportId_=std::make_shared<int32_t>((int32_t)pJson["report_id"].asInt64());
        }
    }
}

const int32_t &AdminReports::getValueOfAdminAccountId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(adminAccountId_)
        return *adminAccountId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &AdminReports::getAdminAccountId() const noexcept
{
    return adminAccountId_;
}
void AdminReports::setAdminAccountId(const int32_t &pAdminAccountId) noexcept
{
    adminAccountId_ = std::make_shared<int32_t>(pAdminAccountId);
    dirtyFlag_[0] = true;
}

const int32_t &AdminReports::getValueOfReportId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(reportId_)
        return *reportId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &AdminReports::getReportId() const noexcept
{
    return reportId_;
}
void AdminReports::setReportId(const int32_t &pReportId) noexcept
{
    reportId_ = std::make_shared<int32_t>(pReportId);
    dirtyFlag_[1] = true;
}

void AdminReports::updateId(const uint64_t id)
{
}
typename AdminReports::PrimaryKeyType AdminReports::getPrimaryKey() const
{
    return std::make_tuple(*adminAccountId_,*reportId_);
}

const std::vector<std::string> &AdminReports::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "admin_account_id",
        "report_id"
    };
    return inCols;
}

void AdminReports::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getAdminAccountId())
        {
            binder << getValueOfAdminAccountId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getReportId())
        {
            binder << getValueOfReportId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> AdminReports::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void AdminReports::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getAdminAccountId())
        {
            binder << getValueOfAdminAccountId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getReportId())
        {
            binder << getValueOfReportId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value AdminReports::toJson() const
{
    Json::Value ret;
    if(getAdminAccountId())
    {
        ret["admin_account_id"]=getValueOfAdminAccountId();
    }
    else
    {
        ret["admin_account_id"]=Json::Value();
    }
    if(getReportId())
    {
        ret["report_id"]=getValueOfReportId();
    }
    else
    {
        ret["report_id"]=Json::Value();
    }
    return ret;
}

std::string AdminReports::toString() const
{
    return toJson().toStyledString();
}

Json::Value AdminReports::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getAdminAccountId())
            {
                ret[pMasqueradingVector[0]]=getValueOfAdminAccountId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getReportId())
            {
                ret[pMasqueradingVector[1]]=getValueOfReportId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getAdminAccountId())
    {
        ret["admin_account_id"]=getValueOfAdminAccountId();
    }
    else
    {
        ret["admin_account_id"]=Json::Value();
    }
    if(getReportId())
    {
        ret["report_id"]=getValueOfReportId();
    }
    else
    {
        ret["report_id"]=Json::Value();
    }
    return ret;
}

bool AdminReports::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("admin_account_id"))
    {
        if(!validJsonOfField(0, "admin_account_id", pJson["admin_account_id"], err, true))
            return false;
    }
    else
    {
        err="The admin_account_id column cannot be null";
        return false;
    }
    if(pJson.isMember("report_id"))
    {
        if(!validJsonOfField(1, "report_id", pJson["report_id"], err, true))
            return false;
    }
    else
    {
        err="The report_id column cannot be null";
        return false;
    }
    return true;
}
bool AdminReports::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool AdminReports::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("admin_account_id"))
    {
        if(!validJsonOfField(0, "admin_account_id", pJson["admin_account_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("report_id"))
    {
        if(!validJsonOfField(1, "report_id", pJson["report_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    return true;
}
bool AdminReports::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool AdminReports::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
