/**
 *
 *  Admins.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Admins.h"
#include "Accounts.h"
#include "AdminReports.h"
#include "Reports.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::main;

const std::string Admins::Cols::_account_id = "\"account_id\"";
const std::string Admins::primaryKeyName = "account_id";
const bool Admins::hasPrimaryKey = true;
const std::string Admins::tableName = "\"admins\"";

const std::vector<typename Admins::MetaData> Admins::metaData_={
{"account_id","int32_t","integer",4,0,1,1}
};
const std::string &Admins::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Admins::Admins(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["account_id"].isNull())
        {
            accountId_=std::make_shared<int32_t>(r["account_id"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 1 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            accountId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Admins::Admins(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 1)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            accountId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
}

Admins::Admins(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("account_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["account_id"].isNull())
        {
            accountId_=std::make_shared<int32_t>((int32_t)pJson["account_id"].asInt64());
        }
    }
}

void Admins::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 1)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            accountId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
}

void Admins::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("account_id"))
    {
        if(!pJson["account_id"].isNull())
        {
            accountId_=std::make_shared<int32_t>((int32_t)pJson["account_id"].asInt64());
        }
    }
}

const int32_t &Admins::getValueOfAccountId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(accountId_)
        return *accountId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Admins::getAccountId() const noexcept
{
    return accountId_;
}
void Admins::setAccountId(const int32_t &pAccountId) noexcept
{
    accountId_ = std::make_shared<int32_t>(pAccountId);
    dirtyFlag_[0] = true;
}
const typename Admins::PrimaryKeyType & Admins::getPrimaryKey() const
{
    assert(accountId_);
    return *accountId_;
}

void Admins::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Admins::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "account_id"
    };
    return inCols;
}

void Admins::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getAccountId())
        {
            binder << getValueOfAccountId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Admins::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    return ret;
}

void Admins::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getAccountId())
        {
            binder << getValueOfAccountId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Admins::toJson() const
{
    Json::Value ret;
    if(getAccountId())
    {
        ret["account_id"]=getValueOfAccountId();
    }
    else
    {
        ret["account_id"]=Json::Value();
    }
    return ret;
}

std::string Admins::toString() const
{
    return toJson().toStyledString();
}

Json::Value Admins::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 1)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getAccountId())
            {
                ret[pMasqueradingVector[0]]=getValueOfAccountId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getAccountId())
    {
        ret["account_id"]=getValueOfAccountId();
    }
    else
    {
        ret["account_id"]=Json::Value();
    }
    return ret;
}

bool Admins::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("account_id"))
    {
        if(!validJsonOfField(0, "account_id", pJson["account_id"], err, true))
            return false;
    }
    else
    {
        err="The account_id column cannot be null";
        return false;
    }
    return true;
}
bool Admins::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 1)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Admins::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("account_id"))
    {
        if(!validJsonOfField(0, "account_id", pJson["account_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    return true;
}
bool Admins::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                              const std::vector<std::string> &pMasqueradingVector,
                                              std::string &err)
{
    if(pMasqueradingVector.size() != 1)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Admins::validJsonOfField(size_t index,
                              const std::string &fieldName,
                              const Json::Value &pJson,
                              std::string &err,
                              bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
Accounts Admins::getAccounts(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from accounts where account_id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *accountId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Accounts(r[0]);
}

void Admins::getAccounts(const DbClientPtr &clientPtr,
                         const std::function<void(Accounts)> &rcb,
                         const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from accounts where account_id = $1";
    *clientPtr << sql
               << *accountId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Accounts(r[0]));
                    }
               }
               >> ecb;
}
std::vector<std::pair<Reports,AdminReports>> Admins::getReports(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from reports,admin_reports where admin_reports.admin_account_id = $1 and admin_reports.report_id = reports.report_id";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *accountId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    std::vector<std::pair<Reports,AdminReports>> ret;
    ret.reserve(r.size());
    for (auto const &row : r)
    {
        ret.emplace_back(std::pair<Reports,AdminReports>(
            Reports(row),AdminReports(row,Reports::getColumnNumber())));
    }
    return ret;
}

void Admins::getReports(const DbClientPtr &clientPtr,
                        const std::function<void(std::vector<std::pair<Reports,AdminReports>>)> &rcb,
                        const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from reports,admin_reports where admin_reports.admin_account_id = $1 and admin_reports.report_id = reports.report_id";
    *clientPtr << sql
               << *accountId_
               >> [rcb = std::move(rcb)](const Result &r){
                   std::vector<std::pair<Reports,AdminReports>> ret;
                   ret.reserve(r.size());
                   for (auto const &row : r)
                   {
                       ret.emplace_back(std::pair<Reports,AdminReports>(
                           Reports(row),AdminReports(row,Reports::getColumnNumber())));
                   }
                   rcb(ret);
               }
               >> ecb;
}
