/**
 *
 *  CartItems.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "CartItems.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::main;

const std::string CartItems::Cols::_cart_id = "\"cart_id\"";
const std::string CartItems::Cols::_item_id = "\"item_id\"";
const std::vector<std::string> CartItems::primaryKeyName = {"cart_id","item_id"};
const bool CartItems::hasPrimaryKey = true;
const std::string CartItems::tableName = "\"cart_items\"";

const std::vector<typename CartItems::MetaData> CartItems::metaData_={
{"cart_id","int32_t","integer",4,0,1,1},
{"item_id","int32_t","integer",4,0,1,1}
};
const std::string &CartItems::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
CartItems::CartItems(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["cart_id"].isNull())
        {
            cartId_=std::make_shared<int32_t>(r["cart_id"].as<int32_t>());
        }
        if(!r["item_id"].isNull())
        {
            itemId_=std::make_shared<int32_t>(r["item_id"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            cartId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            itemId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

CartItems::CartItems(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            cartId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            itemId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

CartItems::CartItems(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("cart_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["cart_id"].isNull())
        {
            cartId_=std::make_shared<int32_t>((int32_t)pJson["cart_id"].asInt64());
        }
    }
    if(pJson.isMember("item_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["item_id"].isNull())
        {
            itemId_=std::make_shared<int32_t>((int32_t)pJson["item_id"].asInt64());
        }
    }
}

void CartItems::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            cartId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            itemId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

void CartItems::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("cart_id"))
    {
        if(!pJson["cart_id"].isNull())
        {
            cartId_=std::make_shared<int32_t>((int32_t)pJson["cart_id"].asInt64());
        }
    }
    if(pJson.isMember("item_id"))
    {
        if(!pJson["item_id"].isNull())
        {
            itemId_=std::make_shared<int32_t>((int32_t)pJson["item_id"].asInt64());
        }
    }
}

const int32_t &CartItems::getValueOfCartId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(cartId_)
        return *cartId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &CartItems::getCartId() const noexcept
{
    return cartId_;
}
void CartItems::setCartId(const int32_t &pCartId) noexcept
{
    cartId_ = std::make_shared<int32_t>(pCartId);
    dirtyFlag_[0] = true;
}

const int32_t &CartItems::getValueOfItemId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(itemId_)
        return *itemId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &CartItems::getItemId() const noexcept
{
    return itemId_;
}
void CartItems::setItemId(const int32_t &pItemId) noexcept
{
    itemId_ = std::make_shared<int32_t>(pItemId);
    dirtyFlag_[1] = true;
}

void CartItems::updateId(const uint64_t id)
{
}
typename CartItems::PrimaryKeyType CartItems::getPrimaryKey() const
{
    return std::make_tuple(*cartId_,*itemId_);
}

const std::vector<std::string> &CartItems::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "cart_id",
        "item_id"
    };
    return inCols;
}

void CartItems::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getCartId())
        {
            binder << getValueOfCartId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getItemId())
        {
            binder << getValueOfItemId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> CartItems::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void CartItems::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getCartId())
        {
            binder << getValueOfCartId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getItemId())
        {
            binder << getValueOfItemId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value CartItems::toJson() const
{
    Json::Value ret;
    if(getCartId())
    {
        ret["cart_id"]=getValueOfCartId();
    }
    else
    {
        ret["cart_id"]=Json::Value();
    }
    if(getItemId())
    {
        ret["item_id"]=getValueOfItemId();
    }
    else
    {
        ret["item_id"]=Json::Value();
    }
    return ret;
}

std::string CartItems::toString() const
{
    return toJson().toStyledString();
}

Json::Value CartItems::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getCartId())
            {
                ret[pMasqueradingVector[0]]=getValueOfCartId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getItemId())
            {
                ret[pMasqueradingVector[1]]=getValueOfItemId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getCartId())
    {
        ret["cart_id"]=getValueOfCartId();
    }
    else
    {
        ret["cart_id"]=Json::Value();
    }
    if(getItemId())
    {
        ret["item_id"]=getValueOfItemId();
    }
    else
    {
        ret["item_id"]=Json::Value();
    }
    return ret;
}

bool CartItems::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("cart_id"))
    {
        if(!validJsonOfField(0, "cart_id", pJson["cart_id"], err, true))
            return false;
    }
    else
    {
        err="The cart_id column cannot be null";
        return false;
    }
    if(pJson.isMember("item_id"))
    {
        if(!validJsonOfField(1, "item_id", pJson["item_id"], err, true))
            return false;
    }
    else
    {
        err="The item_id column cannot be null";
        return false;
    }
    return true;
}
bool CartItems::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool CartItems::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("cart_id"))
    {
        if(!validJsonOfField(0, "cart_id", pJson["cart_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("item_id"))
    {
        if(!validJsonOfField(1, "item_id", pJson["item_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    return true;
}
bool CartItems::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool CartItems::validJsonOfField(size_t index,
                                 const std::string &fieldName,
                                 const Json::Value &pJson,
                                 std::string &err,
                                 bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
