/**
 *
 *  Carts.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Carts.h"
#include "CartItems.h"
#include "Items.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::main;

const std::string Carts::Cols::_cart_id = "\"cart_id\"";
const std::string Carts::Cols::_account_id = "\"account_id\"";
const std::string Carts::primaryKeyName = "cart_id";
const bool Carts::hasPrimaryKey = true;
const std::string Carts::tableName = "\"carts\"";

const std::vector<typename Carts::MetaData> Carts::metaData_={
{"cart_id","int32_t","integer",4,1,1,1},
{"account_id","int32_t","integer",4,0,0,0}
};
const std::string &Carts::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Carts::Carts(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["cart_id"].isNull())
        {
            cartId_=std::make_shared<int32_t>(r["cart_id"].as<int32_t>());
        }
        if(!r["account_id"].isNull())
        {
            accountId_=std::make_shared<int32_t>(r["account_id"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            cartId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            accountId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Carts::Carts(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            cartId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            accountId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

Carts::Carts(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("cart_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["cart_id"].isNull())
        {
            cartId_=std::make_shared<int32_t>((int32_t)pJson["cart_id"].asInt64());
        }
    }
    if(pJson.isMember("account_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["account_id"].isNull())
        {
            accountId_=std::make_shared<int32_t>((int32_t)pJson["account_id"].asInt64());
        }
    }
}

void Carts::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            cartId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            accountId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

void Carts::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("cart_id"))
    {
        if(!pJson["cart_id"].isNull())
        {
            cartId_=std::make_shared<int32_t>((int32_t)pJson["cart_id"].asInt64());
        }
    }
    if(pJson.isMember("account_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["account_id"].isNull())
        {
            accountId_=std::make_shared<int32_t>((int32_t)pJson["account_id"].asInt64());
        }
    }
}

const int32_t &Carts::getValueOfCartId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(cartId_)
        return *cartId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Carts::getCartId() const noexcept
{
    return cartId_;
}
void Carts::setCartId(const int32_t &pCartId) noexcept
{
    cartId_ = std::make_shared<int32_t>(pCartId);
    dirtyFlag_[0] = true;
}
const typename Carts::PrimaryKeyType & Carts::getPrimaryKey() const
{
    assert(cartId_);
    return *cartId_;
}

const int32_t &Carts::getValueOfAccountId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(accountId_)
        return *accountId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Carts::getAccountId() const noexcept
{
    return accountId_;
}
void Carts::setAccountId(const int32_t &pAccountId) noexcept
{
    accountId_ = std::make_shared<int32_t>(pAccountId);
    dirtyFlag_[1] = true;
}
void Carts::setAccountIdToNull() noexcept
{
    accountId_.reset();
    dirtyFlag_[1] = true;
}

void Carts::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Carts::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "account_id"
    };
    return inCols;
}

void Carts::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getAccountId())
        {
            binder << getValueOfAccountId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Carts::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void Carts::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getAccountId())
        {
            binder << getValueOfAccountId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Carts::toJson() const
{
    Json::Value ret;
    if(getCartId())
    {
        ret["cart_id"]=getValueOfCartId();
    }
    else
    {
        ret["cart_id"]=Json::Value();
    }
    if(getAccountId())
    {
        ret["account_id"]=getValueOfAccountId();
    }
    else
    {
        ret["account_id"]=Json::Value();
    }
    return ret;
}

std::string Carts::toString() const
{
    return toJson().toStyledString();
}

Json::Value Carts::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getCartId())
            {
                ret[pMasqueradingVector[0]]=getValueOfCartId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getAccountId())
            {
                ret[pMasqueradingVector[1]]=getValueOfAccountId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getCartId())
    {
        ret["cart_id"]=getValueOfCartId();
    }
    else
    {
        ret["cart_id"]=Json::Value();
    }
    if(getAccountId())
    {
        ret["account_id"]=getValueOfAccountId();
    }
    else
    {
        ret["account_id"]=Json::Value();
    }
    return ret;
}

bool Carts::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("cart_id"))
    {
        if(!validJsonOfField(0, "cart_id", pJson["cart_id"], err, true))
            return false;
    }
    if(pJson.isMember("account_id"))
    {
        if(!validJsonOfField(1, "account_id", pJson["account_id"], err, true))
            return false;
    }
    return true;
}
bool Carts::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Carts::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("cart_id"))
    {
        if(!validJsonOfField(0, "cart_id", pJson["cart_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("account_id"))
    {
        if(!validJsonOfField(1, "account_id", pJson["account_id"], err, false))
            return false;
    }
    return true;
}
bool Carts::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Carts::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson,
                             std::string &err,
                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
std::vector<std::pair<Items,CartItems>> Carts::getItems(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from items,cart_items where cart_items.cart_id = $1 and cart_items.item_id = items.item_id";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *cartId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    std::vector<std::pair<Items,CartItems>> ret;
    ret.reserve(r.size());
    for (auto const &row : r)
    {
        ret.emplace_back(std::pair<Items,CartItems>(
            Items(row),CartItems(row,Items::getColumnNumber())));
    }
    return ret;
}

void Carts::getItems(const DbClientPtr &clientPtr,
                     const std::function<void(std::vector<std::pair<Items,CartItems>>)> &rcb,
                     const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from items,cart_items where cart_items.cart_id = $1 and cart_items.item_id = items.item_id";
    *clientPtr << sql
               << *cartId_
               >> [rcb = std::move(rcb)](const Result &r){
                   std::vector<std::pair<Items,CartItems>> ret;
                   ret.reserve(r.size());
                   for (auto const &row : r)
                   {
                       ret.emplace_back(std::pair<Items,CartItems>(
                           Items(row),CartItems(row,Items::getColumnNumber())));
                   }
                   rcb(ret);
               }
               >> ecb;
}
