/**
 *
 *  Items.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Items.h"
#include "Accounts.h"
#include "CartItems.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::main;

const std::string Items::Cols::_item_id = "\"item_id\"";
const std::string Items::Cols::_item_name = "\"item_name\"";
const std::string Items::Cols::_category = "\"category\"";
const std::string Items::Cols::_image_path = "\"image_path\"";
const std::string Items::primaryKeyName = "item_id";
const bool Items::hasPrimaryKey = true;
const std::string Items::tableName = "\"items\"";

const std::vector<typename Items::MetaData> Items::metaData_={
{"item_id","int32_t","integer",4,1,1,1},
{"item_name","std::string","character varying",255,0,0,1},
{"category","std::string","character varying",100,0,0,0},
{"image_path","std::string","text",0,0,0,0}
};
const std::string &Items::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Items::Items(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["item_id"].isNull())
        {
            itemId_=std::make_shared<int32_t>(r["item_id"].as<int32_t>());
        }
        if(!r["item_name"].isNull())
        {
            itemName_=std::make_shared<std::string>(r["item_name"].as<std::string>());
        }
        if(!r["category"].isNull())
        {
            category_=std::make_shared<std::string>(r["category"].as<std::string>());
        }
        if(!r["image_path"].isNull())
        {
            imagePath_=std::make_shared<std::string>(r["image_path"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            itemId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            itemName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            category_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            imagePath_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Items::Items(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            itemId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            itemName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            category_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            imagePath_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

Items::Items(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("item_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["item_id"].isNull())
        {
            itemId_=std::make_shared<int32_t>((int32_t)pJson["item_id"].asInt64());
        }
    }
    if(pJson.isMember("item_name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["item_name"].isNull())
        {
            itemName_=std::make_shared<std::string>(pJson["item_name"].asString());
        }
    }
    if(pJson.isMember("category"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["category"].isNull())
        {
            category_=std::make_shared<std::string>(pJson["category"].asString());
        }
    }
    if(pJson.isMember("image_path"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["image_path"].isNull())
        {
            imagePath_=std::make_shared<std::string>(pJson["image_path"].asString());
        }
    }
}

void Items::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            itemId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            itemName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            category_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            imagePath_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

void Items::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("item_id"))
    {
        if(!pJson["item_id"].isNull())
        {
            itemId_=std::make_shared<int32_t>((int32_t)pJson["item_id"].asInt64());
        }
    }
    if(pJson.isMember("item_name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["item_name"].isNull())
        {
            itemName_=std::make_shared<std::string>(pJson["item_name"].asString());
        }
    }
    if(pJson.isMember("category"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["category"].isNull())
        {
            category_=std::make_shared<std::string>(pJson["category"].asString());
        }
    }
    if(pJson.isMember("image_path"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["image_path"].isNull())
        {
            imagePath_=std::make_shared<std::string>(pJson["image_path"].asString());
        }
    }
}

const int32_t &Items::getValueOfItemId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(itemId_)
        return *itemId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Items::getItemId() const noexcept
{
    return itemId_;
}
void Items::setItemId(const int32_t &pItemId) noexcept
{
    itemId_ = std::make_shared<int32_t>(pItemId);
    dirtyFlag_[0] = true;
}
const typename Items::PrimaryKeyType & Items::getPrimaryKey() const
{
    assert(itemId_);
    return *itemId_;
}

const std::string &Items::getValueOfItemName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(itemName_)
        return *itemName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Items::getItemName() const noexcept
{
    return itemName_;
}
void Items::setItemName(const std::string &pItemName) noexcept
{
    itemName_ = std::make_shared<std::string>(pItemName);
    dirtyFlag_[1] = true;
}
void Items::setItemName(std::string &&pItemName) noexcept
{
    itemName_ = std::make_shared<std::string>(std::move(pItemName));
    dirtyFlag_[1] = true;
}

const std::string &Items::getValueOfCategory() const noexcept
{
    static const std::string defaultValue = std::string();
    if(category_)
        return *category_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Items::getCategory() const noexcept
{
    return category_;
}
void Items::setCategory(const std::string &pCategory) noexcept
{
    category_ = std::make_shared<std::string>(pCategory);
    dirtyFlag_[2] = true;
}
void Items::setCategory(std::string &&pCategory) noexcept
{
    category_ = std::make_shared<std::string>(std::move(pCategory));
    dirtyFlag_[2] = true;
}
void Items::setCategoryToNull() noexcept
{
    category_.reset();
    dirtyFlag_[2] = true;
}

const std::string &Items::getValueOfImagePath() const noexcept
{
    static const std::string defaultValue = std::string();
    if(imagePath_)
        return *imagePath_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Items::getImagePath() const noexcept
{
    return imagePath_;
}
void Items::setImagePath(const std::string &pImagePath) noexcept
{
    imagePath_ = std::make_shared<std::string>(pImagePath);
    dirtyFlag_[3] = true;
}
void Items::setImagePath(std::string &&pImagePath) noexcept
{
    imagePath_ = std::make_shared<std::string>(std::move(pImagePath));
    dirtyFlag_[3] = true;
}
void Items::setImagePathToNull() noexcept
{
    imagePath_.reset();
    dirtyFlag_[3] = true;
}

void Items::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Items::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "item_name",
        "category",
        "image_path"
    };
    return inCols;
}

void Items::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getItemName())
        {
            binder << getValueOfItemName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getCategory())
        {
            binder << getValueOfCategory();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getImagePath())
        {
            binder << getValueOfImagePath();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Items::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void Items::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getItemName())
        {
            binder << getValueOfItemName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getCategory())
        {
            binder << getValueOfCategory();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getImagePath())
        {
            binder << getValueOfImagePath();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Items::toJson() const
{
    Json::Value ret;
    if(getItemId())
    {
        ret["item_id"]=getValueOfItemId();
    }
    else
    {
        ret["item_id"]=Json::Value();
    }
    if(getItemName())
    {
        ret["item_name"]=getValueOfItemName();
    }
    else
    {
        ret["item_name"]=Json::Value();
    }
    if(getCategory())
    {
        ret["category"]=getValueOfCategory();
    }
    else
    {
        ret["category"]=Json::Value();
    }
    if(getImagePath())
    {
        ret["image_path"]=getValueOfImagePath();
    }
    else
    {
        ret["image_path"]=Json::Value();
    }
    return ret;
}

std::string Items::toString() const
{
    return toJson().toStyledString();
}

Json::Value Items::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getItemId())
            {
                ret[pMasqueradingVector[0]]=getValueOfItemId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getItemName())
            {
                ret[pMasqueradingVector[1]]=getValueOfItemName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getCategory())
            {
                ret[pMasqueradingVector[2]]=getValueOfCategory();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getImagePath())
            {
                ret[pMasqueradingVector[3]]=getValueOfImagePath();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getItemId())
    {
        ret["item_id"]=getValueOfItemId();
    }
    else
    {
        ret["item_id"]=Json::Value();
    }
    if(getItemName())
    {
        ret["item_name"]=getValueOfItemName();
    }
    else
    {
        ret["item_name"]=Json::Value();
    }
    if(getCategory())
    {
        ret["category"]=getValueOfCategory();
    }
    else
    {
        ret["category"]=Json::Value();
    }
    if(getImagePath())
    {
        ret["image_path"]=getValueOfImagePath();
    }
    else
    {
        ret["image_path"]=Json::Value();
    }
    return ret;
}

bool Items::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("item_id"))
    {
        if(!validJsonOfField(0, "item_id", pJson["item_id"], err, true))
            return false;
    }
    if(pJson.isMember("item_name"))
    {
        if(!validJsonOfField(1, "item_name", pJson["item_name"], err, true))
            return false;
    }
    else
    {
        err="The item_name column cannot be null";
        return false;
    }
    if(pJson.isMember("category"))
    {
        if(!validJsonOfField(2, "category", pJson["category"], err, true))
            return false;
    }
    if(pJson.isMember("image_path"))
    {
        if(!validJsonOfField(3, "image_path", pJson["image_path"], err, true))
            return false;
    }
    return true;
}
bool Items::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Items::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("item_id"))
    {
        if(!validJsonOfField(0, "item_id", pJson["item_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("item_name"))
    {
        if(!validJsonOfField(1, "item_name", pJson["item_name"], err, false))
            return false;
    }
    if(pJson.isMember("category"))
    {
        if(!validJsonOfField(2, "category", pJson["category"], err, false))
            return false;
    }
    if(pJson.isMember("image_path"))
    {
        if(!validJsonOfField(3, "image_path", pJson["image_path"], err, false))
            return false;
    }
    return true;
}
bool Items::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Items::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson,
                             std::string &err,
                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
std::vector<std::pair<Accounts,CartItems>> Items::getAccounts(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from accounts,cart_items where cart_items.item_id = $1 and cart_items.account_id = accounts.account_id";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *itemId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    std::vector<std::pair<Accounts,CartItems>> ret;
    ret.reserve(r.size());
    for (auto const &row : r)
    {
        ret.emplace_back(std::pair<Accounts,CartItems>(
            Accounts(row),CartItems(row,Accounts::getColumnNumber())));
    }
    return ret;
}

void Items::getAccounts(const DbClientPtr &clientPtr,
                        const std::function<void(std::vector<std::pair<Accounts,CartItems>>)> &rcb,
                        const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from accounts,cart_items where cart_items.item_id = $1 and cart_items.account_id = accounts.account_id";
    *clientPtr << sql
               << *itemId_
               >> [rcb = std::move(rcb)](const Result &r){
                   std::vector<std::pair<Accounts,CartItems>> ret;
                   ret.reserve(r.size());
                   for (auto const &row : r)
                   {
                       ret.emplace_back(std::pair<Accounts,CartItems>(
                           Accounts(row),CartItems(row,Accounts::getColumnNumber())));
                   }
                   rcb(ret);
               }
               >> ecb;
}
