/**
 *
 *  PriceEntries.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "PriceEntries.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::main;

const std::string PriceEntries::Cols::_entry_id = "\"entry_id\"";
const std::string PriceEntries::Cols::_item_id = "\"item_id\"";
const std::string PriceEntries::Cols::_store_id = "\"store_id\"";
const std::string PriceEntries::Cols::_receipt_id = "\"receipt_id\"";
const std::string PriceEntries::Cols::_logged_price = "\"logged_price\"";
const std::string PriceEntries::Cols::_upload_date = "\"upload_date\"";
const std::string PriceEntries::Cols::_price_date = "\"price_date\"";
const std::string PriceEntries::primaryKeyName = "entry_id";
const bool PriceEntries::hasPrimaryKey = true;
const std::string PriceEntries::tableName = "\"price_entries\"";

const std::vector<typename PriceEntries::MetaData> PriceEntries::metaData_={
{"entry_id","int32_t","integer",4,1,1,1},
{"item_id","int32_t","integer",4,0,0,0},
{"store_id","int32_t","integer",4,0,0,0},
{"receipt_id","int32_t","integer",4,0,0,0},
{"logged_price","std::string","numeric",0,0,0,1},
{"upload_date","::trantor::Date","timestamp without time zone",0,0,0,0},
{"price_date","::trantor::Date","date",0,0,0,0}
};
const std::string &PriceEntries::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
PriceEntries::PriceEntries(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["entry_id"].isNull())
        {
            entryId_=std::make_shared<int32_t>(r["entry_id"].as<int32_t>());
        }
        if(!r["item_id"].isNull())
        {
            itemId_=std::make_shared<int32_t>(r["item_id"].as<int32_t>());
        }
        if(!r["store_id"].isNull())
        {
            storeId_=std::make_shared<int32_t>(r["store_id"].as<int32_t>());
        }
        if(!r["receipt_id"].isNull())
        {
            receiptId_=std::make_shared<int32_t>(r["receipt_id"].as<int32_t>());
        }
        if(!r["logged_price"].isNull())
        {
            loggedPrice_=std::make_shared<std::string>(r["logged_price"].as<std::string>());
        }
        if(!r["upload_date"].isNull())
        {
            auto timeStr = r["upload_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                uploadDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["price_date"].isNull())
        {
            auto daysStr = r["price_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            priceDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 7 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            entryId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            itemId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            storeId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            receiptId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            loggedPrice_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                uploadDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            priceDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }

}

PriceEntries::PriceEntries(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            entryId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            itemId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            storeId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            receiptId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            loggedPrice_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                uploadDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            priceDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
}

PriceEntries::PriceEntries(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("entry_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["entry_id"].isNull())
        {
            entryId_=std::make_shared<int32_t>((int32_t)pJson["entry_id"].asInt64());
        }
    }
    if(pJson.isMember("item_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["item_id"].isNull())
        {
            itemId_=std::make_shared<int32_t>((int32_t)pJson["item_id"].asInt64());
        }
    }
    if(pJson.isMember("store_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["store_id"].isNull())
        {
            storeId_=std::make_shared<int32_t>((int32_t)pJson["store_id"].asInt64());
        }
    }
    if(pJson.isMember("receipt_id"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["receipt_id"].isNull())
        {
            receiptId_=std::make_shared<int32_t>((int32_t)pJson["receipt_id"].asInt64());
        }
    }
    if(pJson.isMember("logged_price"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["logged_price"].isNull())
        {
            loggedPrice_=std::make_shared<std::string>(pJson["logged_price"].asString());
        }
    }
    if(pJson.isMember("upload_date"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["upload_date"].isNull())
        {
            auto timeStr = pJson["upload_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                uploadDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("price_date"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["price_date"].isNull())
        {
            auto daysStr = pJson["price_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            priceDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
}

void PriceEntries::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            entryId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            itemId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            storeId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            receiptId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            loggedPrice_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                uploadDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            priceDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
}

void PriceEntries::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("entry_id"))
    {
        if(!pJson["entry_id"].isNull())
        {
            entryId_=std::make_shared<int32_t>((int32_t)pJson["entry_id"].asInt64());
        }
    }
    if(pJson.isMember("item_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["item_id"].isNull())
        {
            itemId_=std::make_shared<int32_t>((int32_t)pJson["item_id"].asInt64());
        }
    }
    if(pJson.isMember("store_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["store_id"].isNull())
        {
            storeId_=std::make_shared<int32_t>((int32_t)pJson["store_id"].asInt64());
        }
    }
    if(pJson.isMember("receipt_id"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["receipt_id"].isNull())
        {
            receiptId_=std::make_shared<int32_t>((int32_t)pJson["receipt_id"].asInt64());
        }
    }
    if(pJson.isMember("logged_price"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["logged_price"].isNull())
        {
            loggedPrice_=std::make_shared<std::string>(pJson["logged_price"].asString());
        }
    }
    if(pJson.isMember("upload_date"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["upload_date"].isNull())
        {
            auto timeStr = pJson["upload_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                uploadDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("price_date"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["price_date"].isNull())
        {
            auto daysStr = pJson["price_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            priceDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
}

const int32_t &PriceEntries::getValueOfEntryId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(entryId_)
        return *entryId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PriceEntries::getEntryId() const noexcept
{
    return entryId_;
}
void PriceEntries::setEntryId(const int32_t &pEntryId) noexcept
{
    entryId_ = std::make_shared<int32_t>(pEntryId);
    dirtyFlag_[0] = true;
}
const typename PriceEntries::PrimaryKeyType & PriceEntries::getPrimaryKey() const
{
    assert(entryId_);
    return *entryId_;
}

const int32_t &PriceEntries::getValueOfItemId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(itemId_)
        return *itemId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PriceEntries::getItemId() const noexcept
{
    return itemId_;
}
void PriceEntries::setItemId(const int32_t &pItemId) noexcept
{
    itemId_ = std::make_shared<int32_t>(pItemId);
    dirtyFlag_[1] = true;
}
void PriceEntries::setItemIdToNull() noexcept
{
    itemId_.reset();
    dirtyFlag_[1] = true;
}

const int32_t &PriceEntries::getValueOfStoreId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(storeId_)
        return *storeId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PriceEntries::getStoreId() const noexcept
{
    return storeId_;
}
void PriceEntries::setStoreId(const int32_t &pStoreId) noexcept
{
    storeId_ = std::make_shared<int32_t>(pStoreId);
    dirtyFlag_[2] = true;
}
void PriceEntries::setStoreIdToNull() noexcept
{
    storeId_.reset();
    dirtyFlag_[2] = true;
}

const int32_t &PriceEntries::getValueOfReceiptId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(receiptId_)
        return *receiptId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &PriceEntries::getReceiptId() const noexcept
{
    return receiptId_;
}
void PriceEntries::setReceiptId(const int32_t &pReceiptId) noexcept
{
    receiptId_ = std::make_shared<int32_t>(pReceiptId);
    dirtyFlag_[3] = true;
}
void PriceEntries::setReceiptIdToNull() noexcept
{
    receiptId_.reset();
    dirtyFlag_[3] = true;
}

const std::string &PriceEntries::getValueOfLoggedPrice() const noexcept
{
    static const std::string defaultValue = std::string();
    if(loggedPrice_)
        return *loggedPrice_;
    return defaultValue;
}
const std::shared_ptr<std::string> &PriceEntries::getLoggedPrice() const noexcept
{
    return loggedPrice_;
}
void PriceEntries::setLoggedPrice(const std::string &pLoggedPrice) noexcept
{
    loggedPrice_ = std::make_shared<std::string>(pLoggedPrice);
    dirtyFlag_[4] = true;
}
void PriceEntries::setLoggedPrice(std::string &&pLoggedPrice) noexcept
{
    loggedPrice_ = std::make_shared<std::string>(std::move(pLoggedPrice));
    dirtyFlag_[4] = true;
}

const ::trantor::Date &PriceEntries::getValueOfUploadDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(uploadDate_)
        return *uploadDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &PriceEntries::getUploadDate() const noexcept
{
    return uploadDate_;
}
void PriceEntries::setUploadDate(const ::trantor::Date &pUploadDate) noexcept
{
    uploadDate_ = std::make_shared<::trantor::Date>(pUploadDate);
    dirtyFlag_[5] = true;
}
void PriceEntries::setUploadDateToNull() noexcept
{
    uploadDate_.reset();
    dirtyFlag_[5] = true;
}

const ::trantor::Date &PriceEntries::getValueOfPriceDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(priceDate_)
        return *priceDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &PriceEntries::getPriceDate() const noexcept
{
    return priceDate_;
}
void PriceEntries::setPriceDate(const ::trantor::Date &pPriceDate) noexcept
{
    priceDate_ = std::make_shared<::trantor::Date>(pPriceDate.roundDay());
    dirtyFlag_[6] = true;
}
void PriceEntries::setPriceDateToNull() noexcept
{
    priceDate_.reset();
    dirtyFlag_[6] = true;
}

void PriceEntries::updateId(const uint64_t id)
{
}

const std::vector<std::string> &PriceEntries::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "item_id",
        "store_id",
        "receipt_id",
        "logged_price",
        "upload_date",
        "price_date"
    };
    return inCols;
}

void PriceEntries::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getItemId())
        {
            binder << getValueOfItemId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getStoreId())
        {
            binder << getValueOfStoreId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getReceiptId())
        {
            binder << getValueOfReceiptId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getLoggedPrice())
        {
            binder << getValueOfLoggedPrice();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getUploadDate())
        {
            binder << getValueOfUploadDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getPriceDate())
        {
            binder << getValueOfPriceDate();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> PriceEntries::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    return ret;
}

void PriceEntries::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getItemId())
        {
            binder << getValueOfItemId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getStoreId())
        {
            binder << getValueOfStoreId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getReceiptId())
        {
            binder << getValueOfReceiptId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getLoggedPrice())
        {
            binder << getValueOfLoggedPrice();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getUploadDate())
        {
            binder << getValueOfUploadDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getPriceDate())
        {
            binder << getValueOfPriceDate();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value PriceEntries::toJson() const
{
    Json::Value ret;
    if(getEntryId())
    {
        ret["entry_id"]=getValueOfEntryId();
    }
    else
    {
        ret["entry_id"]=Json::Value();
    }
    if(getItemId())
    {
        ret["item_id"]=getValueOfItemId();
    }
    else
    {
        ret["item_id"]=Json::Value();
    }
    if(getStoreId())
    {
        ret["store_id"]=getValueOfStoreId();
    }
    else
    {
        ret["store_id"]=Json::Value();
    }
    if(getReceiptId())
    {
        ret["receipt_id"]=getValueOfReceiptId();
    }
    else
    {
        ret["receipt_id"]=Json::Value();
    }
    if(getLoggedPrice())
    {
        ret["logged_price"]=getValueOfLoggedPrice();
    }
    else
    {
        ret["logged_price"]=Json::Value();
    }
    if(getUploadDate())
    {
        ret["upload_date"]=getUploadDate()->toDbStringLocal();
    }
    else
    {
        ret["upload_date"]=Json::Value();
    }
    if(getPriceDate())
    {
        ret["price_date"]=getPriceDate()->toDbStringLocal();
    }
    else
    {
        ret["price_date"]=Json::Value();
    }
    return ret;
}

std::string PriceEntries::toString() const
{
    return toJson().toStyledString();
}

Json::Value PriceEntries::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 7)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getEntryId())
            {
                ret[pMasqueradingVector[0]]=getValueOfEntryId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getItemId())
            {
                ret[pMasqueradingVector[1]]=getValueOfItemId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getStoreId())
            {
                ret[pMasqueradingVector[2]]=getValueOfStoreId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getReceiptId())
            {
                ret[pMasqueradingVector[3]]=getValueOfReceiptId();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getLoggedPrice())
            {
                ret[pMasqueradingVector[4]]=getValueOfLoggedPrice();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getUploadDate())
            {
                ret[pMasqueradingVector[5]]=getUploadDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getPriceDate())
            {
                ret[pMasqueradingVector[6]]=getPriceDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getEntryId())
    {
        ret["entry_id"]=getValueOfEntryId();
    }
    else
    {
        ret["entry_id"]=Json::Value();
    }
    if(getItemId())
    {
        ret["item_id"]=getValueOfItemId();
    }
    else
    {
        ret["item_id"]=Json::Value();
    }
    if(getStoreId())
    {
        ret["store_id"]=getValueOfStoreId();
    }
    else
    {
        ret["store_id"]=Json::Value();
    }
    if(getReceiptId())
    {
        ret["receipt_id"]=getValueOfReceiptId();
    }
    else
    {
        ret["receipt_id"]=Json::Value();
    }
    if(getLoggedPrice())
    {
        ret["logged_price"]=getValueOfLoggedPrice();
    }
    else
    {
        ret["logged_price"]=Json::Value();
    }
    if(getUploadDate())
    {
        ret["upload_date"]=getUploadDate()->toDbStringLocal();
    }
    else
    {
        ret["upload_date"]=Json::Value();
    }
    if(getPriceDate())
    {
        ret["price_date"]=getPriceDate()->toDbStringLocal();
    }
    else
    {
        ret["price_date"]=Json::Value();
    }
    return ret;
}

bool PriceEntries::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("entry_id"))
    {
        if(!validJsonOfField(0, "entry_id", pJson["entry_id"], err, true))
            return false;
    }
    if(pJson.isMember("item_id"))
    {
        if(!validJsonOfField(1, "item_id", pJson["item_id"], err, true))
            return false;
    }
    if(pJson.isMember("store_id"))
    {
        if(!validJsonOfField(2, "store_id", pJson["store_id"], err, true))
            return false;
    }
    if(pJson.isMember("receipt_id"))
    {
        if(!validJsonOfField(3, "receipt_id", pJson["receipt_id"], err, true))
            return false;
    }
    if(pJson.isMember("logged_price"))
    {
        if(!validJsonOfField(4, "logged_price", pJson["logged_price"], err, true))
            return false;
    }
    else
    {
        err="The logged_price column cannot be null";
        return false;
    }
    if(pJson.isMember("upload_date"))
    {
        if(!validJsonOfField(5, "upload_date", pJson["upload_date"], err, true))
            return false;
    }
    if(pJson.isMember("price_date"))
    {
        if(!validJsonOfField(6, "price_date", pJson["price_date"], err, true))
            return false;
    }
    return true;
}
bool PriceEntries::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PriceEntries::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("entry_id"))
    {
        if(!validJsonOfField(0, "entry_id", pJson["entry_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("item_id"))
    {
        if(!validJsonOfField(1, "item_id", pJson["item_id"], err, false))
            return false;
    }
    if(pJson.isMember("store_id"))
    {
        if(!validJsonOfField(2, "store_id", pJson["store_id"], err, false))
            return false;
    }
    if(pJson.isMember("receipt_id"))
    {
        if(!validJsonOfField(3, "receipt_id", pJson["receipt_id"], err, false))
            return false;
    }
    if(pJson.isMember("logged_price"))
    {
        if(!validJsonOfField(4, "logged_price", pJson["logged_price"], err, false))
            return false;
    }
    if(pJson.isMember("upload_date"))
    {
        if(!validJsonOfField(5, "upload_date", pJson["upload_date"], err, false))
            return false;
    }
    if(pJson.isMember("price_date"))
    {
        if(!validJsonOfField(6, "price_date", pJson["price_date"], err, false))
            return false;
    }
    return true;
}
bool PriceEntries::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool PriceEntries::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
