/**
 *
 *  Receipts.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Receipts.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::main;

const std::string Receipts::Cols::_receipt_id = "\"receipt_id\"";
const std::string Receipts::Cols::_store_id = "\"store_id\"";
const std::string Receipts::Cols::_user_id = "\"user_id\"";
const std::string Receipts::Cols::_raw_image_file = "\"raw_image_file\"";
const std::string Receipts::Cols::_upload_timestamp = "\"upload_timestamp\"";
const std::string Receipts::Cols::_trust_status = "\"trust_status\"";
const std::string Receipts::primaryKeyName = "receipt_id";
const bool Receipts::hasPrimaryKey = true;
const std::string Receipts::tableName = "\"receipts\"";

const std::vector<typename Receipts::MetaData> Receipts::metaData_={
{"receipt_id","int32_t","integer",4,1,1,1},
{"store_id","int32_t","integer",4,0,0,0},
{"user_id","int32_t","integer",4,0,0,0},
{"raw_image_file","std::string","text",0,0,0,0},
{"upload_timestamp","::trantor::Date","timestamp without time zone",0,0,0,0},
{"trust_status","std::string","character varying",50,0,0,0}
};
const std::string &Receipts::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Receipts::Receipts(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["receipt_id"].isNull())
        {
            receiptId_=std::make_shared<int32_t>(r["receipt_id"].as<int32_t>());
        }
        if(!r["store_id"].isNull())
        {
            storeId_=std::make_shared<int32_t>(r["store_id"].as<int32_t>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>(r["user_id"].as<int32_t>());
        }
        if(!r["raw_image_file"].isNull())
        {
            rawImageFile_=std::make_shared<std::string>(r["raw_image_file"].as<std::string>());
        }
        if(!r["upload_timestamp"].isNull())
        {
            auto timeStr = r["upload_timestamp"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                uploadTimestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["trust_status"].isNull())
        {
            trustStatus_=std::make_shared<std::string>(r["trust_status"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 6 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            receiptId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            storeId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            rawImageFile_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                uploadTimestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            trustStatus_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Receipts::Receipts(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            receiptId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            storeId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            rawImageFile_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                uploadTimestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            trustStatus_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
}

Receipts::Receipts(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("receipt_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["receipt_id"].isNull())
        {
            receiptId_=std::make_shared<int32_t>((int32_t)pJson["receipt_id"].asInt64());
        }
    }
    if(pJson.isMember("store_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["store_id"].isNull())
        {
            storeId_=std::make_shared<int32_t>((int32_t)pJson["store_id"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("raw_image_file"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["raw_image_file"].isNull())
        {
            rawImageFile_=std::make_shared<std::string>(pJson["raw_image_file"].asString());
        }
    }
    if(pJson.isMember("upload_timestamp"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["upload_timestamp"].isNull())
        {
            auto timeStr = pJson["upload_timestamp"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                uploadTimestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("trust_status"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["trust_status"].isNull())
        {
            trustStatus_=std::make_shared<std::string>(pJson["trust_status"].asString());
        }
    }
}

void Receipts::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            receiptId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            storeId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            rawImageFile_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                uploadTimestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            trustStatus_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
}

void Receipts::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("receipt_id"))
    {
        if(!pJson["receipt_id"].isNull())
        {
            receiptId_=std::make_shared<int32_t>((int32_t)pJson["receipt_id"].asInt64());
        }
    }
    if(pJson.isMember("store_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["store_id"].isNull())
        {
            storeId_=std::make_shared<int32_t>((int32_t)pJson["store_id"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("raw_image_file"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["raw_image_file"].isNull())
        {
            rawImageFile_=std::make_shared<std::string>(pJson["raw_image_file"].asString());
        }
    }
    if(pJson.isMember("upload_timestamp"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["upload_timestamp"].isNull())
        {
            auto timeStr = pJson["upload_timestamp"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                uploadTimestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("trust_status"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["trust_status"].isNull())
        {
            trustStatus_=std::make_shared<std::string>(pJson["trust_status"].asString());
        }
    }
}

const int32_t &Receipts::getValueOfReceiptId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(receiptId_)
        return *receiptId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Receipts::getReceiptId() const noexcept
{
    return receiptId_;
}
void Receipts::setReceiptId(const int32_t &pReceiptId) noexcept
{
    receiptId_ = std::make_shared<int32_t>(pReceiptId);
    dirtyFlag_[0] = true;
}
const typename Receipts::PrimaryKeyType & Receipts::getPrimaryKey() const
{
    assert(receiptId_);
    return *receiptId_;
}

const int32_t &Receipts::getValueOfStoreId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(storeId_)
        return *storeId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Receipts::getStoreId() const noexcept
{
    return storeId_;
}
void Receipts::setStoreId(const int32_t &pStoreId) noexcept
{
    storeId_ = std::make_shared<int32_t>(pStoreId);
    dirtyFlag_[1] = true;
}
void Receipts::setStoreIdToNull() noexcept
{
    storeId_.reset();
    dirtyFlag_[1] = true;
}

const int32_t &Receipts::getValueOfUserId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Receipts::getUserId() const noexcept
{
    return userId_;
}
void Receipts::setUserId(const int32_t &pUserId) noexcept
{
    userId_ = std::make_shared<int32_t>(pUserId);
    dirtyFlag_[2] = true;
}
void Receipts::setUserIdToNull() noexcept
{
    userId_.reset();
    dirtyFlag_[2] = true;
}

const std::string &Receipts::getValueOfRawImageFile() const noexcept
{
    static const std::string defaultValue = std::string();
    if(rawImageFile_)
        return *rawImageFile_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Receipts::getRawImageFile() const noexcept
{
    return rawImageFile_;
}
void Receipts::setRawImageFile(const std::string &pRawImageFile) noexcept
{
    rawImageFile_ = std::make_shared<std::string>(pRawImageFile);
    dirtyFlag_[3] = true;
}
void Receipts::setRawImageFile(std::string &&pRawImageFile) noexcept
{
    rawImageFile_ = std::make_shared<std::string>(std::move(pRawImageFile));
    dirtyFlag_[3] = true;
}
void Receipts::setRawImageFileToNull() noexcept
{
    rawImageFile_.reset();
    dirtyFlag_[3] = true;
}

const ::trantor::Date &Receipts::getValueOfUploadTimestamp() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(uploadTimestamp_)
        return *uploadTimestamp_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Receipts::getUploadTimestamp() const noexcept
{
    return uploadTimestamp_;
}
void Receipts::setUploadTimestamp(const ::trantor::Date &pUploadTimestamp) noexcept
{
    uploadTimestamp_ = std::make_shared<::trantor::Date>(pUploadTimestamp);
    dirtyFlag_[4] = true;
}
void Receipts::setUploadTimestampToNull() noexcept
{
    uploadTimestamp_.reset();
    dirtyFlag_[4] = true;
}

const std::string &Receipts::getValueOfTrustStatus() const noexcept
{
    static const std::string defaultValue = std::string();
    if(trustStatus_)
        return *trustStatus_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Receipts::getTrustStatus() const noexcept
{
    return trustStatus_;
}
void Receipts::setTrustStatus(const std::string &pTrustStatus) noexcept
{
    trustStatus_ = std::make_shared<std::string>(pTrustStatus);
    dirtyFlag_[5] = true;
}
void Receipts::setTrustStatus(std::string &&pTrustStatus) noexcept
{
    trustStatus_ = std::make_shared<std::string>(std::move(pTrustStatus));
    dirtyFlag_[5] = true;
}
void Receipts::setTrustStatusToNull() noexcept
{
    trustStatus_.reset();
    dirtyFlag_[5] = true;
}

void Receipts::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Receipts::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "store_id",
        "user_id",
        "raw_image_file",
        "upload_timestamp",
        "trust_status"
    };
    return inCols;
}

void Receipts::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getStoreId())
        {
            binder << getValueOfStoreId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getRawImageFile())
        {
            binder << getValueOfRawImageFile();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getUploadTimestamp())
        {
            binder << getValueOfUploadTimestamp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getTrustStatus())
        {
            binder << getValueOfTrustStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Receipts::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void Receipts::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getStoreId())
        {
            binder << getValueOfStoreId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getRawImageFile())
        {
            binder << getValueOfRawImageFile();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getUploadTimestamp())
        {
            binder << getValueOfUploadTimestamp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getTrustStatus())
        {
            binder << getValueOfTrustStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Receipts::toJson() const
{
    Json::Value ret;
    if(getReceiptId())
    {
        ret["receipt_id"]=getValueOfReceiptId();
    }
    else
    {
        ret["receipt_id"]=Json::Value();
    }
    if(getStoreId())
    {
        ret["store_id"]=getValueOfStoreId();
    }
    else
    {
        ret["store_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getRawImageFile())
    {
        ret["raw_image_file"]=getValueOfRawImageFile();
    }
    else
    {
        ret["raw_image_file"]=Json::Value();
    }
    if(getUploadTimestamp())
    {
        ret["upload_timestamp"]=getUploadTimestamp()->toDbStringLocal();
    }
    else
    {
        ret["upload_timestamp"]=Json::Value();
    }
    if(getTrustStatus())
    {
        ret["trust_status"]=getValueOfTrustStatus();
    }
    else
    {
        ret["trust_status"]=Json::Value();
    }
    return ret;
}

std::string Receipts::toString() const
{
    return toJson().toStyledString();
}

Json::Value Receipts::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 6)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getReceiptId())
            {
                ret[pMasqueradingVector[0]]=getValueOfReceiptId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getStoreId())
            {
                ret[pMasqueradingVector[1]]=getValueOfStoreId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[2]]=getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getRawImageFile())
            {
                ret[pMasqueradingVector[3]]=getValueOfRawImageFile();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getUploadTimestamp())
            {
                ret[pMasqueradingVector[4]]=getUploadTimestamp()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getTrustStatus())
            {
                ret[pMasqueradingVector[5]]=getValueOfTrustStatus();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getReceiptId())
    {
        ret["receipt_id"]=getValueOfReceiptId();
    }
    else
    {
        ret["receipt_id"]=Json::Value();
    }
    if(getStoreId())
    {
        ret["store_id"]=getValueOfStoreId();
    }
    else
    {
        ret["store_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getRawImageFile())
    {
        ret["raw_image_file"]=getValueOfRawImageFile();
    }
    else
    {
        ret["raw_image_file"]=Json::Value();
    }
    if(getUploadTimestamp())
    {
        ret["upload_timestamp"]=getUploadTimestamp()->toDbStringLocal();
    }
    else
    {
        ret["upload_timestamp"]=Json::Value();
    }
    if(getTrustStatus())
    {
        ret["trust_status"]=getValueOfTrustStatus();
    }
    else
    {
        ret["trust_status"]=Json::Value();
    }
    return ret;
}

bool Receipts::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("receipt_id"))
    {
        if(!validJsonOfField(0, "receipt_id", pJson["receipt_id"], err, true))
            return false;
    }
    if(pJson.isMember("store_id"))
    {
        if(!validJsonOfField(1, "store_id", pJson["store_id"], err, true))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(2, "user_id", pJson["user_id"], err, true))
            return false;
    }
    if(pJson.isMember("raw_image_file"))
    {
        if(!validJsonOfField(3, "raw_image_file", pJson["raw_image_file"], err, true))
            return false;
    }
    if(pJson.isMember("upload_timestamp"))
    {
        if(!validJsonOfField(4, "upload_timestamp", pJson["upload_timestamp"], err, true))
            return false;
    }
    if(pJson.isMember("trust_status"))
    {
        if(!validJsonOfField(5, "trust_status", pJson["trust_status"], err, true))
            return false;
    }
    return true;
}
bool Receipts::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Receipts::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("receipt_id"))
    {
        if(!validJsonOfField(0, "receipt_id", pJson["receipt_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("store_id"))
    {
        if(!validJsonOfField(1, "store_id", pJson["store_id"], err, false))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(2, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("raw_image_file"))
    {
        if(!validJsonOfField(3, "raw_image_file", pJson["raw_image_file"], err, false))
            return false;
    }
    if(pJson.isMember("upload_timestamp"))
    {
        if(!validJsonOfField(4, "upload_timestamp", pJson["upload_timestamp"], err, false))
            return false;
    }
    if(pJson.isMember("trust_status"))
    {
        if(!validJsonOfField(5, "trust_status", pJson["trust_status"], err, false))
            return false;
    }
    return true;
}
bool Receipts::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Receipts::validJsonOfField(size_t index,
                                const std::string &fieldName,
                                const Json::Value &pJson,
                                std::string &err,
                                bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
