/**
 *
 *  Reports.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Reports.h"
#include "AdminReports.h"
#include "Admins.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::main;

const std::string Reports::Cols::_report_id = "\"report_id\"";
const std::string Reports::Cols::_reporter_account_id = "\"reporter_account_id\"";
const std::string Reports::Cols::_price_entry_id = "\"price_entry_id\"";
const std::string Reports::Cols::_reason_for_report = "\"reason_for_report\"";
const std::string Reports::Cols::_report_timestamp = "\"report_timestamp\"";
const std::string Reports::Cols::_resolution_status = "\"resolution_status\"";
const std::string Reports::primaryKeyName = "report_id";
const bool Reports::hasPrimaryKey = true;
const std::string Reports::tableName = "\"reports\"";

const std::vector<typename Reports::MetaData> Reports::metaData_={
{"report_id","int32_t","integer",4,1,1,1},
{"reporter_account_id","int32_t","integer",4,0,0,0},
{"price_entry_id","int32_t","integer",4,0,0,0},
{"reason_for_report","std::string","text",0,0,0,0},
{"report_timestamp","::trantor::Date","timestamp without time zone",0,0,0,0},
{"resolution_status","std::string","character varying",50,0,0,0}
};
const std::string &Reports::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Reports::Reports(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["report_id"].isNull())
        {
            reportId_=std::make_shared<int32_t>(r["report_id"].as<int32_t>());
        }
        if(!r["reporter_account_id"].isNull())
        {
            reporterAccountId_=std::make_shared<int32_t>(r["reporter_account_id"].as<int32_t>());
        }
        if(!r["price_entry_id"].isNull())
        {
            priceEntryId_=std::make_shared<int32_t>(r["price_entry_id"].as<int32_t>());
        }
        if(!r["reason_for_report"].isNull())
        {
            reasonForReport_=std::make_shared<std::string>(r["reason_for_report"].as<std::string>());
        }
        if(!r["report_timestamp"].isNull())
        {
            auto timeStr = r["report_timestamp"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                reportTimestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["resolution_status"].isNull())
        {
            resolutionStatus_=std::make_shared<std::string>(r["resolution_status"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 6 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            reportId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            reporterAccountId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            priceEntryId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            reasonForReport_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                reportTimestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            resolutionStatus_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Reports::Reports(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            reportId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            reporterAccountId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            priceEntryId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            reasonForReport_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                reportTimestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            resolutionStatus_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
}

Reports::Reports(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("report_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["report_id"].isNull())
        {
            reportId_=std::make_shared<int32_t>((int32_t)pJson["report_id"].asInt64());
        }
    }
    if(pJson.isMember("reporter_account_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["reporter_account_id"].isNull())
        {
            reporterAccountId_=std::make_shared<int32_t>((int32_t)pJson["reporter_account_id"].asInt64());
        }
    }
    if(pJson.isMember("price_entry_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["price_entry_id"].isNull())
        {
            priceEntryId_=std::make_shared<int32_t>((int32_t)pJson["price_entry_id"].asInt64());
        }
    }
    if(pJson.isMember("reason_for_report"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["reason_for_report"].isNull())
        {
            reasonForReport_=std::make_shared<std::string>(pJson["reason_for_report"].asString());
        }
    }
    if(pJson.isMember("report_timestamp"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["report_timestamp"].isNull())
        {
            auto timeStr = pJson["report_timestamp"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                reportTimestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("resolution_status"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["resolution_status"].isNull())
        {
            resolutionStatus_=std::make_shared<std::string>(pJson["resolution_status"].asString());
        }
    }
}

void Reports::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            reportId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            reporterAccountId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            priceEntryId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            reasonForReport_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                reportTimestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            resolutionStatus_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
}

void Reports::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("report_id"))
    {
        if(!pJson["report_id"].isNull())
        {
            reportId_=std::make_shared<int32_t>((int32_t)pJson["report_id"].asInt64());
        }
    }
    if(pJson.isMember("reporter_account_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["reporter_account_id"].isNull())
        {
            reporterAccountId_=std::make_shared<int32_t>((int32_t)pJson["reporter_account_id"].asInt64());
        }
    }
    if(pJson.isMember("price_entry_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["price_entry_id"].isNull())
        {
            priceEntryId_=std::make_shared<int32_t>((int32_t)pJson["price_entry_id"].asInt64());
        }
    }
    if(pJson.isMember("reason_for_report"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["reason_for_report"].isNull())
        {
            reasonForReport_=std::make_shared<std::string>(pJson["reason_for_report"].asString());
        }
    }
    if(pJson.isMember("report_timestamp"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["report_timestamp"].isNull())
        {
            auto timeStr = pJson["report_timestamp"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                reportTimestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("resolution_status"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["resolution_status"].isNull())
        {
            resolutionStatus_=std::make_shared<std::string>(pJson["resolution_status"].asString());
        }
    }
}

const int32_t &Reports::getValueOfReportId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(reportId_)
        return *reportId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Reports::getReportId() const noexcept
{
    return reportId_;
}
void Reports::setReportId(const int32_t &pReportId) noexcept
{
    reportId_ = std::make_shared<int32_t>(pReportId);
    dirtyFlag_[0] = true;
}
const typename Reports::PrimaryKeyType & Reports::getPrimaryKey() const
{
    assert(reportId_);
    return *reportId_;
}

const int32_t &Reports::getValueOfReporterAccountId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(reporterAccountId_)
        return *reporterAccountId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Reports::getReporterAccountId() const noexcept
{
    return reporterAccountId_;
}
void Reports::setReporterAccountId(const int32_t &pReporterAccountId) noexcept
{
    reporterAccountId_ = std::make_shared<int32_t>(pReporterAccountId);
    dirtyFlag_[1] = true;
}
void Reports::setReporterAccountIdToNull() noexcept
{
    reporterAccountId_.reset();
    dirtyFlag_[1] = true;
}

const int32_t &Reports::getValueOfPriceEntryId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(priceEntryId_)
        return *priceEntryId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Reports::getPriceEntryId() const noexcept
{
    return priceEntryId_;
}
void Reports::setPriceEntryId(const int32_t &pPriceEntryId) noexcept
{
    priceEntryId_ = std::make_shared<int32_t>(pPriceEntryId);
    dirtyFlag_[2] = true;
}
void Reports::setPriceEntryIdToNull() noexcept
{
    priceEntryId_.reset();
    dirtyFlag_[2] = true;
}

const std::string &Reports::getValueOfReasonForReport() const noexcept
{
    static const std::string defaultValue = std::string();
    if(reasonForReport_)
        return *reasonForReport_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Reports::getReasonForReport() const noexcept
{
    return reasonForReport_;
}
void Reports::setReasonForReport(const std::string &pReasonForReport) noexcept
{
    reasonForReport_ = std::make_shared<std::string>(pReasonForReport);
    dirtyFlag_[3] = true;
}
void Reports::setReasonForReport(std::string &&pReasonForReport) noexcept
{
    reasonForReport_ = std::make_shared<std::string>(std::move(pReasonForReport));
    dirtyFlag_[3] = true;
}
void Reports::setReasonForReportToNull() noexcept
{
    reasonForReport_.reset();
    dirtyFlag_[3] = true;
}

const ::trantor::Date &Reports::getValueOfReportTimestamp() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(reportTimestamp_)
        return *reportTimestamp_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Reports::getReportTimestamp() const noexcept
{
    return reportTimestamp_;
}
void Reports::setReportTimestamp(const ::trantor::Date &pReportTimestamp) noexcept
{
    reportTimestamp_ = std::make_shared<::trantor::Date>(pReportTimestamp);
    dirtyFlag_[4] = true;
}
void Reports::setReportTimestampToNull() noexcept
{
    reportTimestamp_.reset();
    dirtyFlag_[4] = true;
}

const std::string &Reports::getValueOfResolutionStatus() const noexcept
{
    static const std::string defaultValue = std::string();
    if(resolutionStatus_)
        return *resolutionStatus_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Reports::getResolutionStatus() const noexcept
{
    return resolutionStatus_;
}
void Reports::setResolutionStatus(const std::string &pResolutionStatus) noexcept
{
    resolutionStatus_ = std::make_shared<std::string>(pResolutionStatus);
    dirtyFlag_[5] = true;
}
void Reports::setResolutionStatus(std::string &&pResolutionStatus) noexcept
{
    resolutionStatus_ = std::make_shared<std::string>(std::move(pResolutionStatus));
    dirtyFlag_[5] = true;
}
void Reports::setResolutionStatusToNull() noexcept
{
    resolutionStatus_.reset();
    dirtyFlag_[5] = true;
}

void Reports::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Reports::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "reporter_account_id",
        "price_entry_id",
        "reason_for_report",
        "report_timestamp",
        "resolution_status"
    };
    return inCols;
}

void Reports::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getReporterAccountId())
        {
            binder << getValueOfReporterAccountId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPriceEntryId())
        {
            binder << getValueOfPriceEntryId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getReasonForReport())
        {
            binder << getValueOfReasonForReport();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getReportTimestamp())
        {
            binder << getValueOfReportTimestamp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getResolutionStatus())
        {
            binder << getValueOfResolutionStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Reports::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void Reports::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getReporterAccountId())
        {
            binder << getValueOfReporterAccountId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPriceEntryId())
        {
            binder << getValueOfPriceEntryId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getReasonForReport())
        {
            binder << getValueOfReasonForReport();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getReportTimestamp())
        {
            binder << getValueOfReportTimestamp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getResolutionStatus())
        {
            binder << getValueOfResolutionStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Reports::toJson() const
{
    Json::Value ret;
    if(getReportId())
    {
        ret["report_id"]=getValueOfReportId();
    }
    else
    {
        ret["report_id"]=Json::Value();
    }
    if(getReporterAccountId())
    {
        ret["reporter_account_id"]=getValueOfReporterAccountId();
    }
    else
    {
        ret["reporter_account_id"]=Json::Value();
    }
    if(getPriceEntryId())
    {
        ret["price_entry_id"]=getValueOfPriceEntryId();
    }
    else
    {
        ret["price_entry_id"]=Json::Value();
    }
    if(getReasonForReport())
    {
        ret["reason_for_report"]=getValueOfReasonForReport();
    }
    else
    {
        ret["reason_for_report"]=Json::Value();
    }
    if(getReportTimestamp())
    {
        ret["report_timestamp"]=getReportTimestamp()->toDbStringLocal();
    }
    else
    {
        ret["report_timestamp"]=Json::Value();
    }
    if(getResolutionStatus())
    {
        ret["resolution_status"]=getValueOfResolutionStatus();
    }
    else
    {
        ret["resolution_status"]=Json::Value();
    }
    return ret;
}

std::string Reports::toString() const
{
    return toJson().toStyledString();
}

Json::Value Reports::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 6)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getReportId())
            {
                ret[pMasqueradingVector[0]]=getValueOfReportId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getReporterAccountId())
            {
                ret[pMasqueradingVector[1]]=getValueOfReporterAccountId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getPriceEntryId())
            {
                ret[pMasqueradingVector[2]]=getValueOfPriceEntryId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getReasonForReport())
            {
                ret[pMasqueradingVector[3]]=getValueOfReasonForReport();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getReportTimestamp())
            {
                ret[pMasqueradingVector[4]]=getReportTimestamp()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getResolutionStatus())
            {
                ret[pMasqueradingVector[5]]=getValueOfResolutionStatus();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getReportId())
    {
        ret["report_id"]=getValueOfReportId();
    }
    else
    {
        ret["report_id"]=Json::Value();
    }
    if(getReporterAccountId())
    {
        ret["reporter_account_id"]=getValueOfReporterAccountId();
    }
    else
    {
        ret["reporter_account_id"]=Json::Value();
    }
    if(getPriceEntryId())
    {
        ret["price_entry_id"]=getValueOfPriceEntryId();
    }
    else
    {
        ret["price_entry_id"]=Json::Value();
    }
    if(getReasonForReport())
    {
        ret["reason_for_report"]=getValueOfReasonForReport();
    }
    else
    {
        ret["reason_for_report"]=Json::Value();
    }
    if(getReportTimestamp())
    {
        ret["report_timestamp"]=getReportTimestamp()->toDbStringLocal();
    }
    else
    {
        ret["report_timestamp"]=Json::Value();
    }
    if(getResolutionStatus())
    {
        ret["resolution_status"]=getValueOfResolutionStatus();
    }
    else
    {
        ret["resolution_status"]=Json::Value();
    }
    return ret;
}

bool Reports::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("report_id"))
    {
        if(!validJsonOfField(0, "report_id", pJson["report_id"], err, true))
            return false;
    }
    if(pJson.isMember("reporter_account_id"))
    {
        if(!validJsonOfField(1, "reporter_account_id", pJson["reporter_account_id"], err, true))
            return false;
    }
    if(pJson.isMember("price_entry_id"))
    {
        if(!validJsonOfField(2, "price_entry_id", pJson["price_entry_id"], err, true))
            return false;
    }
    if(pJson.isMember("reason_for_report"))
    {
        if(!validJsonOfField(3, "reason_for_report", pJson["reason_for_report"], err, true))
            return false;
    }
    if(pJson.isMember("report_timestamp"))
    {
        if(!validJsonOfField(4, "report_timestamp", pJson["report_timestamp"], err, true))
            return false;
    }
    if(pJson.isMember("resolution_status"))
    {
        if(!validJsonOfField(5, "resolution_status", pJson["resolution_status"], err, true))
            return false;
    }
    return true;
}
bool Reports::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Reports::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("report_id"))
    {
        if(!validJsonOfField(0, "report_id", pJson["report_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("reporter_account_id"))
    {
        if(!validJsonOfField(1, "reporter_account_id", pJson["reporter_account_id"], err, false))
            return false;
    }
    if(pJson.isMember("price_entry_id"))
    {
        if(!validJsonOfField(2, "price_entry_id", pJson["price_entry_id"], err, false))
            return false;
    }
    if(pJson.isMember("reason_for_report"))
    {
        if(!validJsonOfField(3, "reason_for_report", pJson["reason_for_report"], err, false))
            return false;
    }
    if(pJson.isMember("report_timestamp"))
    {
        if(!validJsonOfField(4, "report_timestamp", pJson["report_timestamp"], err, false))
            return false;
    }
    if(pJson.isMember("resolution_status"))
    {
        if(!validJsonOfField(5, "resolution_status", pJson["resolution_status"], err, false))
            return false;
    }
    return true;
}
bool Reports::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Reports::validJsonOfField(size_t index,
                               const std::string &fieldName,
                               const Json::Value &pJson,
                               std::string &err,
                               bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
std::vector<std::pair<Admins,AdminReports>> Reports::getAdmins(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from admins,admin_reports where admin_reports.report_id = $1 and admin_reports.admin_account_id = admins.account_id";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *reportId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    std::vector<std::pair<Admins,AdminReports>> ret;
    ret.reserve(r.size());
    for (auto const &row : r)
    {
        ret.emplace_back(std::pair<Admins,AdminReports>(
            Admins(row),AdminReports(row,Admins::getColumnNumber())));
    }
    return ret;
}

void Reports::getAdmins(const DbClientPtr &clientPtr,
                        const std::function<void(std::vector<std::pair<Admins,AdminReports>>)> &rcb,
                        const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from admins,admin_reports where admin_reports.report_id = $1 and admin_reports.admin_account_id = admins.account_id";
    *clientPtr << sql
               << *reportId_
               >> [rcb = std::move(rcb)](const Result &r){
                   std::vector<std::pair<Admins,AdminReports>> ret;
                   ret.reserve(r.size());
                   for (auto const &row : r)
                   {
                       ret.emplace_back(std::pair<Admins,AdminReports>(
                           Admins(row),AdminReports(row,Admins::getColumnNumber())));
                   }
                   rcb(ret);
               }
               >> ecb;
}
