/**
 *
 *  Reports.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace main
{
class AdminReports;
class Admins;

class Reports
{
  public:
    struct Cols
    {
        static const std::string _report_id;
        static const std::string _reporter_account_id;
        static const std::string _price_entry_id;
        static const std::string _reason_for_report;
        static const std::string _report_timestamp;
        static const std::string _resolution_status;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Reports(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Reports(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Reports(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Reports() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column report_id  */
    ///Get the value of the column report_id, returns the default value if the column is null
    const int32_t &getValueOfReportId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getReportId() const noexcept;
    ///Set the value of the column report_id
    void setReportId(const int32_t &pReportId) noexcept;

    /**  For column reporter_account_id  */
    ///Get the value of the column reporter_account_id, returns the default value if the column is null
    const int32_t &getValueOfReporterAccountId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getReporterAccountId() const noexcept;
    ///Set the value of the column reporter_account_id
    void setReporterAccountId(const int32_t &pReporterAccountId) noexcept;
    void setReporterAccountIdToNull() noexcept;

    /**  For column price_entry_id  */
    ///Get the value of the column price_entry_id, returns the default value if the column is null
    const int32_t &getValueOfPriceEntryId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getPriceEntryId() const noexcept;
    ///Set the value of the column price_entry_id
    void setPriceEntryId(const int32_t &pPriceEntryId) noexcept;
    void setPriceEntryIdToNull() noexcept;

    /**  For column reason_for_report  */
    ///Get the value of the column reason_for_report, returns the default value if the column is null
    const std::string &getValueOfReasonForReport() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getReasonForReport() const noexcept;
    ///Set the value of the column reason_for_report
    void setReasonForReport(const std::string &pReasonForReport) noexcept;
    void setReasonForReport(std::string &&pReasonForReport) noexcept;
    void setReasonForReportToNull() noexcept;

    /**  For column report_timestamp  */
    ///Get the value of the column report_timestamp, returns the default value if the column is null
    const ::trantor::Date &getValueOfReportTimestamp() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getReportTimestamp() const noexcept;
    ///Set the value of the column report_timestamp
    void setReportTimestamp(const ::trantor::Date &pReportTimestamp) noexcept;
    void setReportTimestampToNull() noexcept;

    /**  For column resolution_status  */
    ///Get the value of the column resolution_status, returns the default value if the column is null
    const std::string &getValueOfResolutionStatus() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getResolutionStatus() const noexcept;
    ///Set the value of the column resolution_status
    void setResolutionStatus(const std::string &pResolutionStatus) noexcept;
    void setResolutionStatus(std::string &&pResolutionStatus) noexcept;
    void setResolutionStatusToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 6;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    std::vector<std::pair<Admins,AdminReports>> getAdmins(const drogon::orm::DbClientPtr &clientPtr) const;
    void getAdmins(const drogon::orm::DbClientPtr &clientPtr,
                   const std::function<void(std::vector<std::pair<Admins,AdminReports>>)> &rcb,
                   const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<Reports>;
    friend drogon::orm::BaseBuilder<Reports, true, true>;
    friend drogon::orm::BaseBuilder<Reports, true, false>;
    friend drogon::orm::BaseBuilder<Reports, false, true>;
    friend drogon::orm::BaseBuilder<Reports, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Reports>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> reportId_;
    std::shared_ptr<int32_t> reporterAccountId_;
    std::shared_ptr<int32_t> priceEntryId_;
    std::shared_ptr<std::string> reasonForReport_;
    std::shared_ptr<::trantor::Date> reportTimestamp_;
    std::shared_ptr<std::string> resolutionStatus_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[6]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where report_id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where report_id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "report_id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "reporter_account_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "price_entry_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "reason_for_report,";
            ++parametersCount;
        }
        sql += "report_timestamp,";
        ++parametersCount;
        if(!dirtyFlag_[4])
        {
            needSelection=true;
        }
        sql += "resolution_status,";
        ++parametersCount;
        if(!dirtyFlag_[5])
        {
            needSelection=true;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace main
} // namespace drogon_model
