/**
 *
 *  StoreOwners.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "StoreOwners.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::main;

const std::string StoreOwners::Cols::_account_id = "\"account_id\"";
const std::string StoreOwners::Cols::_store_id = "\"store_id\"";
const std::string StoreOwners::Cols::_is_verified = "\"is_verified\"";
const std::string StoreOwners::primaryKeyName = "account_id";
const bool StoreOwners::hasPrimaryKey = true;
const std::string StoreOwners::tableName = "\"store_owners\"";

const std::vector<typename StoreOwners::MetaData> StoreOwners::metaData_={
{"account_id","int32_t","integer",4,0,1,1},
{"store_id","int32_t","integer",4,0,0,0},
{"is_verified","bool","boolean",1,0,0,0}
};
const std::string &StoreOwners::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
StoreOwners::StoreOwners(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["account_id"].isNull())
        {
            accountId_=std::make_shared<int32_t>(r["account_id"].as<int32_t>());
        }
        if(!r["store_id"].isNull())
        {
            storeId_=std::make_shared<int32_t>(r["store_id"].as<int32_t>());
        }
        if(!r["is_verified"].isNull())
        {
            isVerified_=std::make_shared<bool>(r["is_verified"].as<bool>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            accountId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            storeId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            isVerified_=std::make_shared<bool>(r[index].as<bool>());
        }
    }

}

StoreOwners::StoreOwners(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            accountId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            storeId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            isVerified_=std::make_shared<bool>(pJson[pMasqueradingVector[2]].asBool());
        }
    }
}

StoreOwners::StoreOwners(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("account_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["account_id"].isNull())
        {
            accountId_=std::make_shared<int32_t>((int32_t)pJson["account_id"].asInt64());
        }
    }
    if(pJson.isMember("store_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["store_id"].isNull())
        {
            storeId_=std::make_shared<int32_t>((int32_t)pJson["store_id"].asInt64());
        }
    }
    if(pJson.isMember("is_verified"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["is_verified"].isNull())
        {
            isVerified_=std::make_shared<bool>(pJson["is_verified"].asBool());
        }
    }
}

void StoreOwners::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            accountId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            storeId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            isVerified_=std::make_shared<bool>(pJson[pMasqueradingVector[2]].asBool());
        }
    }
}

void StoreOwners::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("account_id"))
    {
        if(!pJson["account_id"].isNull())
        {
            accountId_=std::make_shared<int32_t>((int32_t)pJson["account_id"].asInt64());
        }
    }
    if(pJson.isMember("store_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["store_id"].isNull())
        {
            storeId_=std::make_shared<int32_t>((int32_t)pJson["store_id"].asInt64());
        }
    }
    if(pJson.isMember("is_verified"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["is_verified"].isNull())
        {
            isVerified_=std::make_shared<bool>(pJson["is_verified"].asBool());
        }
    }
}

const int32_t &StoreOwners::getValueOfAccountId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(accountId_)
        return *accountId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &StoreOwners::getAccountId() const noexcept
{
    return accountId_;
}
void StoreOwners::setAccountId(const int32_t &pAccountId) noexcept
{
    accountId_ = std::make_shared<int32_t>(pAccountId);
    dirtyFlag_[0] = true;
}
const typename StoreOwners::PrimaryKeyType & StoreOwners::getPrimaryKey() const
{
    assert(accountId_);
    return *accountId_;
}

const int32_t &StoreOwners::getValueOfStoreId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(storeId_)
        return *storeId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &StoreOwners::getStoreId() const noexcept
{
    return storeId_;
}
void StoreOwners::setStoreId(const int32_t &pStoreId) noexcept
{
    storeId_ = std::make_shared<int32_t>(pStoreId);
    dirtyFlag_[1] = true;
}
void StoreOwners::setStoreIdToNull() noexcept
{
    storeId_.reset();
    dirtyFlag_[1] = true;
}

const bool &StoreOwners::getValueOfIsVerified() const noexcept
{
    static const bool defaultValue = bool();
    if(isVerified_)
        return *isVerified_;
    return defaultValue;
}
const std::shared_ptr<bool> &StoreOwners::getIsVerified() const noexcept
{
    return isVerified_;
}
void StoreOwners::setIsVerified(const bool &pIsVerified) noexcept
{
    isVerified_ = std::make_shared<bool>(pIsVerified);
    dirtyFlag_[2] = true;
}
void StoreOwners::setIsVerifiedToNull() noexcept
{
    isVerified_.reset();
    dirtyFlag_[2] = true;
}

void StoreOwners::updateId(const uint64_t id)
{
}

const std::vector<std::string> &StoreOwners::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "account_id",
        "store_id",
        "is_verified"
    };
    return inCols;
}

void StoreOwners::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getAccountId())
        {
            binder << getValueOfAccountId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getStoreId())
        {
            binder << getValueOfStoreId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getIsVerified())
        {
            binder << getValueOfIsVerified();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> StoreOwners::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void StoreOwners::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getAccountId())
        {
            binder << getValueOfAccountId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getStoreId())
        {
            binder << getValueOfStoreId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getIsVerified())
        {
            binder << getValueOfIsVerified();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value StoreOwners::toJson() const
{
    Json::Value ret;
    if(getAccountId())
    {
        ret["account_id"]=getValueOfAccountId();
    }
    else
    {
        ret["account_id"]=Json::Value();
    }
    if(getStoreId())
    {
        ret["store_id"]=getValueOfStoreId();
    }
    else
    {
        ret["store_id"]=Json::Value();
    }
    if(getIsVerified())
    {
        ret["is_verified"]=getValueOfIsVerified();
    }
    else
    {
        ret["is_verified"]=Json::Value();
    }
    return ret;
}

std::string StoreOwners::toString() const
{
    return toJson().toStyledString();
}

Json::Value StoreOwners::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getAccountId())
            {
                ret[pMasqueradingVector[0]]=getValueOfAccountId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getStoreId())
            {
                ret[pMasqueradingVector[1]]=getValueOfStoreId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getIsVerified())
            {
                ret[pMasqueradingVector[2]]=getValueOfIsVerified();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getAccountId())
    {
        ret["account_id"]=getValueOfAccountId();
    }
    else
    {
        ret["account_id"]=Json::Value();
    }
    if(getStoreId())
    {
        ret["store_id"]=getValueOfStoreId();
    }
    else
    {
        ret["store_id"]=Json::Value();
    }
    if(getIsVerified())
    {
        ret["is_verified"]=getValueOfIsVerified();
    }
    else
    {
        ret["is_verified"]=Json::Value();
    }
    return ret;
}

bool StoreOwners::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("account_id"))
    {
        if(!validJsonOfField(0, "account_id", pJson["account_id"], err, true))
            return false;
    }
    else
    {
        err="The account_id column cannot be null";
        return false;
    }
    if(pJson.isMember("store_id"))
    {
        if(!validJsonOfField(1, "store_id", pJson["store_id"], err, true))
            return false;
    }
    if(pJson.isMember("is_verified"))
    {
        if(!validJsonOfField(2, "is_verified", pJson["is_verified"], err, true))
            return false;
    }
    return true;
}
bool StoreOwners::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool StoreOwners::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("account_id"))
    {
        if(!validJsonOfField(0, "account_id", pJson["account_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("store_id"))
    {
        if(!validJsonOfField(1, "store_id", pJson["store_id"], err, false))
            return false;
    }
    if(pJson.isMember("is_verified"))
    {
        if(!validJsonOfField(2, "is_verified", pJson["is_verified"], err, false))
            return false;
    }
    return true;
}
bool StoreOwners::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool StoreOwners::validJsonOfField(size_t index,
                                   const std::string &fieldName,
                                   const Json::Value &pJson,
                                   std::string &err,
                                   bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
